apiVersion: apps/v1
kind: Deployment
metadata:
  name: userinfo
  namespace: rony-hms

spec:
  replicas: 1

  selector:
    matchLabels:
      app: userinfo

  template:
    metadata:
      labels:
        app: userinfo

    spec:
      containers:
      - name: userinfo

        image: 816069140701.dkr.ecr.ap-south-1.amazonaws.com/rony-hms/userinfo-service:v1.0.0

        imagePullPolicy: Always

        ports:
        - containerPort: 9093

        startupProbe:
          httpGet:
            path: /actuator/health
            port: 9093
          failureThreshold: 60
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 9093
          initialDelaySeconds: 20
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 9093
          initialDelaySeconds: 30
          periodSeconds: 20

        env:

        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: userinfo-config
              key: SPRING_DATASOURCE_URL

        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              name: userinfo-config
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE

        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: userinfo-config
              key: SERVER_PORT

        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: userinfo-secret
              key: SPRING_DATASOURCE_USERNAME

        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: userinfo-secret
              key: SPRING_DATASOURCE_PASSWORD

        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"

          limits:
            memory: "1Gi"
            cpu: "500m"